import os
import google.generativeai as genai

genai.configure(api_key=("Google Generative AI API Key"))


model = genai.GenerativeModel("gemini-2.5-flash")
from fastapi import FastAPI, Depends, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session

import models
import schemas
from database import SessionLocal, engine

models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# TEMPORARY CORS SETTINGS FOR TESTING
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@app.get("/")
def root():
    return {
        "message": "Customer Complaint Management System API is running!"
    }


@app.get("/complaints")
def get_complaints(db: Session = Depends(get_db)):
    complaints = db.query(models.Complaint).all()
    return complaints


@app.post("/complaints")
def create_complaint(
    complaint: schemas.ComplaintCreate,
    db: Session = Depends(get_db)
):
    new_complaint = models.Complaint(
        name=complaint.name,
        email=complaint.email,
        category=complaint.category,
        complaint=complaint.complaint,
        status="Open"
    )

    db.add(new_complaint)
    db.commit()
    db.refresh(new_complaint)

    return {
        "message": "Complaint submitted successfully",
        "data": new_complaint
    }

@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    content = await file.read()

    return {
        "filename": file.filename,
        "size": len(content),
        "message": "File uploaded successfully"
    }


# ADD THIS BELOW THE UPLOAD ENDPOINT

@app.post("/ai/analyze")
async def analyze_complaint(request: schemas.AIRequest):

    prompt = f"""
Return ONLY valid JSON in this format:

{{
  "summary": "",
  "risk": "",
  "root_cause": "",
  "recommendation": ""
}}

Complaint:
{request.complaint}
"""

    try:
        response = model.generate_content(prompt)

        import json
        import re

        text = response.text.strip()

        # Remove Markdown code fences if Gemini returns them
        text = re.sub(r"^```json\s*", "", text)
        text = re.sub(r"\s*```$", "", text)

        return json.loads(text)

    except Exception as e:
        return {
            "summary": f"Gemini Error: {str(e)}",
            "risk": "Unknown",
            "root_cause": "AI request failed",
            "recommendation": "Check Gemini configuration."
        }
@app.post("/ai/chat")
async def chat_with_ai(request: schemas.ChatRequest):
    prompt = f"""
You are an AI assistant for pharmaceutical complaint management.

Complaint:
{request.complaint}

User Question:
{request.question}

Answer only based on the complaint.
"""

    try:
        response = model.generate_content(prompt)
        return {
            "answer": response.text
        }
    except Exception as e:
        return {
            "answer": f"Gemini Error: {str(e)}"
        }
        return {
        "summary": text,
        "risk": "AI Generated",
        "root_cause": "Generated by Gemini",
        "recommendation": "See AI response above."
}